import type { Metadata } from "next";
import "./globals.css";
import { MathJaxContext } from "better-react-mathjax";
import { Toaster } from 'react-hot-toast';
import { Inter } from 'next/font/google'


const inter = Inter({ subsets: ['latin'], variable: '--font-sans' })

export const metadata: Metadata = {
  title: "Sav AI",
  description: "Generated by create next app",
};

const mathJaxConfig = {
  tex: { inlineMath: [['$', '$'], ['\$$', '\$$']] },
  svg: { fontCache: 'global' }
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body
        className={'antialiased min-h-screen font-sans min-w-screen' }
      >
        <Toaster
          position="top-center"
          toastOptions={{
            style: {
              backdropFilter: 'blur(20px)', // Apply blur effect
              WebkitBackdropFilter: 'blur(20px)', // Safari support
              color: '#333', // Text color
              borderRadius: '8px', // Rounded corners
              fontSize: '14px', // Adjust font size
              padding: '12px 16px', // Add spacing
              backgroundColor: 'rgba(255, 255, 255, 0.5)', // Solid white background for default
            },
            success: {
              style: {
                background: 'rgba(255, 255, 255, 0.5)', // Opaque white for success
                color: '#333', // Dark text for contrast
              },
            },
            error: {
              style: {
                backgroundColor: 'rgba(255, 255, 255, 0.1) !important',
                color: 'black', // White text
              },
            },
          }}
        />

        <MathJaxContext
          version={3}
          config={mathJaxConfig}
        >


          {children}


        </MathJaxContext>
      </body>
    </html>
  );
}
